### PR TITLE
more comprehensive tracking of local modules

### PR DESCRIPTION
**Pull request by rcgoodfellow**
Module support in u-root works by partitioning modules into local and
external. Local modules have an associated rewrite rule in the go mod
file and their sources are copied into the temporary u-root build area.
In the current code this becomes problematic in the following situation.
Consider the following dependency chains.

rygoo/cmds/my-uroot-prog -> alice/pkg/audio -> bob/pkg/stereo
rygoo/cmds/my-uroot-prog -> bob/pkg/mono

In this situation, I will get the code for /bob/pkg/mono copied, but
not the code for bob/pkg/stereo and u-root will fail to compile my
module. This is because the locality of modules does not take into
account any modules that were considered to be local due to other imports.
This patch builds a set of local modules beforehand and decides to copy
code if the base of the module is in this pre-computed set rather than
only considering the current import context.

We've been testing this code with success in our staging environment.

### CODE REVIEW

**Comment by hugelgupf** [comment]
Oh good point. Thanks! I'm trying to set up some better testing for this in a different repo ('cause once you have a go.mod at the top-level, you can't have vendor-only stuff below...)

**Comment by hugelgupf** [comment]
hey @rcgoodfellow I actually don't understand your example. is there a repo somewhere or something you could share?

**Comment by rcgoodfellow** [comment]
Hi @hugelgupf you should be able to hit this with the following

```
u-root \
-format=cpio \
-build=bb -o ginitramfs.cpio  \
-defaultsh /bbin/rush \
github.com/u-root/u-root/cmds/core/{ls,ip,cat,echo,kexec,kill,ping,shutdown,cp,mkdir,rm,init,chmod,lsmod,insmod,rmmod,dmesg,wget} \ 
github.com/u-root/u-root/cmds/exp/{rush,modprobe} \
gitlab.com/mergetb/tech/sled/cmds/dhclient \
gitlab.com/mergetb/tech/sled/sledc
```
This currently returns the following for us
```
2019/11/14 15:05:14 Disabling CGO for u-root...
2019/11/14 15:05:14 Build environment: GOARCH=amd64 GOOS=linux GOPATH=/home/ry/go CGO_ENABLED=0 GO111MODULE= GOROOT=/usr/local/go PATH=/usr/local/go/bin:/home/ry/.local/bin:/home/ry/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ry/.local/bin:/usr/local/go/bin:/home/ry/go/bin:/home/ry/bin:/home/ry/.local/bin
2019/11/14 15:05:14 Filename is ginitramfs.cpio
2019/11/14 15:05:36 Preserving bb temporary directory at /tmp/bb-579636276 due to error
2019/11/14 15:05:36 error building: error building go package in "/tmp/bb-579636276/src/bb": go: finding github.com/u-root/u-root/pkg/rand latest
go: finding github.com/u-root/u-root/pkg latest
build bb.u-root.com/src/bb: cannot load github.com/u-root/u-root/pkg/rand: cannot find module providing package github.com/u-root/u-root/pkg/rand
, exit status 1
```
but builds fine in the PR branch.

Thanks

**Comment by hugelgupf** [comment]
Hey! Thank you for the pointer. I'm picking this work back up again, and moving to a separate repo for testing reasons (u-root will have a /go.mod, which means we can't really test vendoring). You can follow along at https://github.com/u-root/gobusybox.

**Comment by hugelgupf** [comment]
Your test case informed a large part of the dependency design, I'm working on dependency conflict resolution today and making sure it returns sane error messages with suggestions.

**Pull request closed without merging**
